const products=[
    {
    id:1,
    title:'Steelers',
    description:'The original 1933 team was named the Pirates after the city’s major league baseball team. In 1940, Owner Art Rooney Sr. changed the team name to Steelers to more properly represent the city’s dominant steel industry',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:20,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145846.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-pittsburgh-steelers-team-logo-2-300x300.png",
},{
    id:2,
    title:'Bengals',
    description:'Paul Brown selected the name because there had once been a pro football team in Cincinnati named the Bengals and adopting that name “would provide a link with past professional football in Cincinnati.',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:1,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145849.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-cincinnati-bengals-team-logo-300x300.png",
},
{
    id:3,
    title:'Buccaners',
    description:'A team advisory board reviewed 400 name possibilities and selected Buccaneers.',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:3,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145844.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-tampa-bay-buccaneers-team-logo-2-300x300.png",
},
{
    id:4,
    title:'SeeHawks',
    description:'The nickname Seahawks was the result of a fan contest that drew 20,365 entries and suggested 1,742 different names. Seahawks was suggested by 151 entrants and judged by the team ownership as the best choice',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:4,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145846.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-seattle-seahawks-team-logo-2-300x300.png",
},
{
    id:5,
    title:'Ravens',
    description:'On March 29, 1996, Baltimore’s NFL team became the Ravens. The nickname was selected from among three finalists in a poll conducted by the Baltimore Sun. Baltimore fans selected the name in honor of Edgar Allan Poe, the American poet who penned his famous poem, “The Raven” while living in Baltimore.',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:20,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145847.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-baltimore-ravens-team-logo-2-300x300.png",
},{
    id:6,
    title:'Bears',
    description:' When this team became a charter member of the American Professional Football Association (APFA) in 1920, the team was located in Decatur, IL, and was named after team sponsor, the Staley Starch Company. The team moved to Chicago in 1921 and became the Chicago Staleys. In 1922, after team founder-manager and star end George Halas purchased the team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:1,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145842.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-chicago-bears-team-logo-2-300x300.png",
},
{
    id:7,
    title:'Cowboys',
    description:'In the initial months following the its formation, the Dallas team was known as the “Steers.” After a few weeks, however, the name was changed to “Rangers.” At the same time, a baseball team operated in Dallas under that name, but was scheduled to fold before the 1960 football season. ',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:3,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145848.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-dallas-cowboys-team-logo-2-300x300.png",
},
{
    id:8,
    title:'Panthers',
    description:'Team owner Jerry Richardson’s son Mark is responsible for the selection of Panthers as the team name. Mark, who felt that there should be some “synergy” between the name and the team colors also suggested the team colors of black, blue and silver',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:4,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145846.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-carolina-panthers-team-logo-2-300x300.png",
},
{
    id:9,
    title:'Texans',
    description:'fter Houston was awarded the NFL 32nd franchise on October 6, 1999, a series of focus groups were formed to help come up with a nickname for the team. On March 2, 2000, the team announced five choices, the Apollos, Bobcats, Stallions, Texans and Wildcatters. The list was then shaved to the Apollos, Stallions and Texans a month later',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:20,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145845.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-houston-texans-team-logo-2-300x300.png",
},{
    id:10,
    title:'Patriots',
    description:'The new AFL team originally located in Boston, was named the Patriots because of the area’s heritage as the birthplace of the American Revolution',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:1,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145850.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-new-england-patriots-team-logo-2-300x300.png",
},
{
    id:11,
    title:`49er's`,
    description:'The 49ers name was adopted when San Francisco obtained an AAFC franchise in 1946. The name was selected as a recognition of the pioneering and adventurous spirit of the men of the 1849 gold rush in the Sierra Nevada mountains east of San Francisco',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:3,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145845.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-san-francisco-49ers-team-logo-2-300x300.png",
},
{
    id:12,
    title:'Chiefs',
    description:'The AFL franchise began in 1960 as the Dallas Texans. When the team was moved to Kansas City in 1963, the new name was selected by a fan contest',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:4,
    SubmitterAvatarUrl:"https://image.flaticon.com/icons/svg/145/145843.svg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-kansas-city-chiefs-team-logo-2-300x300.png",
},
]

export  default products;