const products=[
    {
    id:1,
    title:'Steelers',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:20,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-pittsburgh-steelers-team-logo-2-300x300.png",
},{
    id:2,
    title:'Bengals',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:1,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-cincinnati-bengals-team-logo-300x300.png",
},
{
    id:3,
    title:'Buccaners',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:3,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-tampa-bay-buccaneers-team-logo-2-300x300.png",
},
{
    id:4,
    title:'SeeHawks',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:4,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-seattle-seahawks-team-logo-2-300x300.png",
},
{
    id:5,
    title:'Ravens',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:20,
    SubmitterAvatarUrl:"https://www.vexels.com/png-svg/preview/141801/baltimore-ravens-american-football",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-baltimore-ravens-team-logo-2-300x300.png",
},{
    id:6,
    title:'Bears',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:1,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-chicago-bears-team-logo-2-300x300.png",
},
{
    id:7,
    title:'Cowboys',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:3,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-dallas-cowboys-team-logo-2-300x300.png",
},
{
    id:8,
    title:'Panthers',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:4,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-carolina-panthers-team-logo-2-300x300.png",
},
{
    id:9,
    title:'Texans',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:20,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-houston-texans-team-logo-2-300x300.png",
},{
    id:10,
    title:'Patriots',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:1,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-new-england-patriots-team-logo-2-300x300.png",
},
{
    id:11,
    title:`49er's`,
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:3,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-san-francisco-49ers-team-logo-2-300x300.png",
},
{
    id:12,
    title:'Chiefs',
    description:'6 time super bowl team',
    url:'https://en.wikipedia.org/wiki/Pittsburgh_Steelers',
    votes:4,
    SubmitterAvatarUrl:"https://static.comicvine.com/uploads/scale_small/0/7823/470124-yujiro_hanma_picture_clear.jpg",
    productImageUrl:"http://loodibee.com/wp-content/uploads/nfl-kansas-city-chiefs-team-logo-2-300x300.png",
},
]

export  default products;